package com.example.format

import com.example.model.*
import com.example.tools.PrimitiveGenerator
import androidx.compose.ui.graphics.Color
import java.io.InputStream

object FbxFormat {

    fun parseFbx(inputStream: InputStream, filename: String = "Imported.fbx"): Scene3D {
        val text = String(inputStream.readBytes(), Charsets.UTF_8)
        val vertices = mutableListOf<Vertex>()
        val faces = mutableListOf<Face>()

        // Search for FBX ASCII "Vertices:" array or "PolygonVertexIndex:" array
        if (text.contains("Vertices:") || text.contains("Objects:")) {
            val vMatch = Regex("Vertices:\\s*\\*\\d+\\s*\\{\\s*a:\\s*([\\d\\.,eE\\-\\s]+)").find(text)
            if (vMatch != null) {
                val coords = vMatch.groupValues[1].split(",").mapNotNull { it.trim().toFloatOrNull() }
                for (i in 0 until coords.size - 2 step 3) {
                    vertices.add(Vertex(position = Vector3(coords[i], coords[i + 1], coords[i + 2])))
                }
            }

            val pMatch = Regex("PolygonVertexIndex:\\s*\\*\\d+\\s*\\{\\s*a:\\s*([\\-\\d\\.,\\s]+)").find(text)
            if (pMatch != null) {
                val indices = pMatch.groupValues[1].split(",").mapNotNull { it.trim().toIntOrNull() }
                var poly = mutableListOf<Int>()
                for (idx in indices) {
                    if (idx < 0) {
                        // FBX uses bitwise NOT (~idx) for polygon end index
                        poly.add((-idx) - 1)
                        if (poly.size >= 3) {
                            faces.add(Face(v1 = poly[0], v2 = poly[1], v3 = poly[2]))
                        }
                        poly = mutableListOf()
                    } else {
                        poly.add(idx)
                    }
                }
            }
        }

        val name = filename.substringBeforeLast(".")
        val mesh = if (vertices.isNotEmpty() && faces.isNotEmpty()) {
            Mesh3D(
                id = "fbx_mesh_0",
                name = name,
                vertices = vertices,
                faces = faces,
                material = Material3D(name = "$name Material", baseColor = Color(0xFF818CF8))
            )
        } else {
            PrimitiveGenerator.generateCube(name = name)
        }

        return Scene3D(
            meshes = listOf(mesh),
            skeleton = Skeleton(
                bones = listOf(
                    Bone(id = 0, name = "FBX_Root", length = 0.5f),
                    Bone(id = 1, name = "FBX_Arm_L", parentId = 0, length = 1.0f, restPosition = Vector3(-0.8f, 0.5f, 0f)),
                    Bone(id = 2, name = "FBX_Arm_R", parentId = 0, length = 1.0f, restPosition = Vector3(0.8f, 0.5f, 0f))
                )
            )
        )
    }

    fun exportFbx(scene: Scene3D): String {
        val sb = StringBuilder()
        sb.append("; FBX 7.4.0 project export generated by PolyStudio 3D Android\n")
        sb.append("FBXHeaderExtension:  {\n")
        sb.append("    FBXHeaderVersion: 1008000\n")
        sb.append("    Creator: \"PolyStudio 3D Engine\"\n")
        sb.append("}\n\n")

        sb.append("Objects:  {\n")
        scene.meshes.forEachIndexed { mIdx, mesh ->
            sb.append("    Model: \"Model::${mesh.name}\", \"Mesh\" {\n")
            sb.append("        Version: 232\n")
            sb.append("        Vertices: *${mesh.vertices.size * 3} {\n")
            sb.append("            a: ")

            val modelMat = mesh.getModelMatrix()
            val coordsStr = mesh.vertices.joinToString(",") { v ->
                val p = modelMat.transformVector(v.position)
                "${p.x},${p.y},${p.z}"
            }
            sb.append(coordsStr).append("\n")
            sb.append("        }\n")

            sb.append("        PolygonVertexIndex: *${mesh.faces.size * 3} {\n")
            sb.append("            a: ")
            val polyIndicesStr = mesh.faces.joinToString(",") { f ->
                // Last index is negated in FBX (~v3)
                "${f.v1},${f.v2},${(-f.v3) - 1}"
            }
            sb.append(polyIndicesStr).append("\n")
            sb.append("        }\n")
            sb.append("    }\n")
        }

        // Export Bones
        scene.skeleton.bones.forEach { bone ->
            sb.append("    NodeAttribute: \"NodeAttribute::${bone.name}_Att\", \"LimbNode\" {\n")
            sb.append("        TypeFlags: \"Skeleton\"\n")
            sb.append("    }\n")
            sb.append("    Model: \"Model::${bone.name}\", \"LimbNode\" {\n")
            sb.append("        Properties70:  {\n")
            sb.append("            P: \"Lcl Translation\", \"Lcl Translation\", \"\", \"A\",${bone.position.x},${bone.position.y},${bone.position.z}\n")
            sb.append("            P: \"Lcl Rotation\", \"Lcl Rotation\", \"\", \"A\",${bone.rotation.x},${bone.rotation.y},${bone.rotation.z}\n")
            sb.append("        }\n")
            sb.append("    }\n")
        }

        sb.append("}\n")
        return sb.toString()
    }
}
