package com.example.format

import com.example.model.*
import androidx.compose.ui.graphics.Color

object ObjFormat {

    fun parseObj(text: String, filename: String = "ImportedModel.obj"): Scene3D? {
        val vertices = mutableListOf<Vertex>()
        val faces = mutableListOf<Face>()
        val rawPositions = mutableListOf<Vector3>()
        val rawNormals = mutableListOf<Vector3>()

        text.lineSequence().forEach { line ->
            val trimmed = line.trim()
            if (trimmed.startsWith("v ")) {
                val parts = trimmed.substring(2).trim().split("\\s+".toRegex())
                if (parts.size >= 3) {
                    val x = parts[0].toFloatOrNull() ?: 0f
                    val y = parts[1].toFloatOrNull() ?: 0f
                    val z = parts[2].toFloatOrNull() ?: 0f
                    rawPositions.add(Vector3(x, y, z))
                }
            } else if (trimmed.startsWith("vn ")) {
                val parts = trimmed.substring(3).trim().split("\\s+".toRegex())
                if (parts.size >= 3) {
                    val x = parts[0].toFloatOrNull() ?: 0f
                    val y = parts[1].toFloatOrNull() ?: 0f
                    val z = parts[2].toFloatOrNull() ?: 0f
                    rawNormals.add(Vector3(x, y, z).normalized())
                }
            } else if (trimmed.startsWith("f ")) {
                val parts = trimmed.substring(2).trim().split("\\s+".toRegex())
                val indices = mutableListOf<Int>()
                parts.forEach { part ->
                    val vertexIndexStr = part.split("/")[0]
                    val idx = (vertexIndexStr.toIntOrNull() ?: 1) - 1
                    if (idx in rawPositions.indices) {
                        indices.add(idx)
                    }
                }
                if (indices.size >= 3) {
                    // Triangulate polygon fan
                    for (i in 1 until indices.size - 1) {
                        faces.add(Face(v1 = indices[0], v2 = indices[i], v3 = indices[i + 1]))
                    }
                }
            }
        }

        if (rawPositions.isEmpty()) return null

        rawPositions.forEachIndexed { idx, pos ->
            val norm = rawNormals.getOrNull(idx) ?: Vector3(0f, 1f, 0f)
            vertices.add(Vertex(position = pos, normal = norm, color = Color(0xFFA855F7)))
        }

        val name = filename.substringBeforeLast(".")
        val mesh = Mesh3D(
            id = "obj_mesh_0",
            name = name,
            vertices = vertices,
            faces = faces,
            material = Material3D(name = "$name Material", baseColor = Color(0xFFA855F7))
        )

        return Scene3D(meshes = listOf(mesh))
    }

    fun exportObj(scene: Scene3D): String {
        val sb = StringBuilder()
        sb.append("# OBJ export generated by PolyStudio 3D Android\n")

        var vertexOffset = 1

        scene.meshes.forEach { mesh ->
            sb.append("o ${mesh.name}\n")
            val modelMat = mesh.getModelMatrix()

            mesh.vertices.forEach { v ->
                val p = modelMat.transformVector(v.position)
                sb.append("v ${p.x} ${p.y} ${p.z}\n")
            }

            mesh.vertices.forEach { v ->
                val n = modelMat.transformDirection(v.normal)
                sb.append("vn ${n.x} ${n.y} ${n.z}\n")
            }

            mesh.faces.forEach { f ->
                val v1 = f.v1 + vertexOffset
                val v2 = f.v2 + vertexOffset
                val v3 = f.v3 + vertexOffset
                sb.append("f $v1//$v1 $v2//$v2 $v3//$v3\n")
            }

            vertexOffset += mesh.vertices.size
        }

        return sb.toString()
    }
}
